name: Minify static site

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install html-minifier and terser
      run: |
        npm install -g html-minifier terser clean-css-cli

    - name: Minify HTML, CSS, JS
      run: |
        find . -name "*.html" -exec html-minifier --collapse-whitespace --remove-comments --minify-js true --minify-css true -o {} {} \;
        find . -name "*.css" -exec cleancss -o {} {} \;
        find . -name "*.js" -exec terser {} -o {} \;

    - name: Push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Minify site

